# Generated by Django 5.0.4 on 2025-08-18 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('cliente_nome', models.CharField(max_length=100)),
                ('cliente_email', models.EmailField(max_length=254)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_emissao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('quantidade', models.IntegerField()),
                ('unidade', models.CharField(default='UND', max_length=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='lojaApp.fatura')),
            ],
        ),
    ]
