# Generated by Django 5.0.4 on 2025-08-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaApp', '0002_fatura_produtofatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='cliente_endereco',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fatura',
            name='cliente_nif',
            field=models.CharField(default='RUA E', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fatura',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
