# Generated by Django 5.0.4 on 2025-08-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaApp', '0003_fatura_cliente_endereco_fatura_cliente_nif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
